# Lista de Exercícios — Pandas

Nesta atividade, cada grupo utilizará um dataset diferente. As respostas devem ser obtidas utilizando a biblioteca Pandas.

In [5]:
import pandas as pd
import matplotlib.pyplot as plt

# Carregue seu dataset abaixo
# Exemplo:
# df = pd.read_csv('dataset.csv')

df = pd.read_csv('sample_data/phishing_dataset.csv')

df.head()

,url,length_url,length_hostname,ip,nb_dots,nb_hyphens,nb_at,nb_qm,nb_and,nb_or,...,domain_in_title,domain_with_copyright,whois_registered_domain,domain_registration_length,domain_age,web_traffic,dns_record,google_index,page_rank,status
0,http://www.crestonwood.com/router.php,37,19,0,3,0,0,0,0,0,...,0,1,0,45,-1,0,1,1,4,legitimate
1,http://shadetreetechnology.com/V4/validation/a...,77,23,1,1,0,0,0,0,0,...,1,0,0,77,5767,0,0,1,2,phishing
2,https://support-appleld.com.secureupdate.duila...,126,50,1,4,1,0,1,2,0,...,1,0,0,14,4004,5828815,0,1,0,phishing
3,http://rgipt.ac.in,18,11,0,2,0,0,0,0,0,...,1,0,0,62,-1,107721,0,0,3,legitimate
4,http://www.iracing.com/tracks/gateway-motorspo...,55,15,0,2,2,0,0,0,0,...,0,1,0,224,8175,8725,0,0,6,legitimate

## 1. Exploração Inicial

### Questão 1

Quantas linhas e colunas existem no dataset?

In [ ]:
df.shape

### Questão 2

Quais são os nomes das colunas?

In [26]:
df.columns

Index(['url', 'length_url', 'length_hostname', 'ip', 'nb_dots', 'nb_hyphens',
       'nb_at', 'nb_qm', 'nb_and', 'nb_or', 'nb_eq', 'nb_underscore',
       'nb_tilde', 'nb_percent', 'nb_slash', 'nb_star', 'nb_colon', 'nb_comma',
       'nb_semicolumn', 'nb_dollar', 'nb_space', 'nb_www', 'nb_com',
       'nb_dslash', 'http_in_path', 'https_token', 'ratio_digits_url',
       'ratio_digits_host', 'punycode', 'port', 'tld_in_path',
       'tld_in_subdomain', 'abnormal_subdomain', 'nb_subdomains',
       'prefix_suffix', 'random_domain', 'shortening_service',
       'path_extension', 'nb_redirection', 'nb_external_redirection',
       'length_words_raw', 'char_repeat', 'shortest_words_raw',
       'shortest_word_host', 'shortest_word_path', 'longest_words_raw',
       'longest_word_host', 'longest_word_path', 'avg_words_raw',
       'avg_word_host', 'avg_word_path', 'phish_hints', 'domain_in_brand',
       'brand_in_subdomain', 'brand_in_path', 'suspecious_tld',
       'statistical_report', 'nb_hyperlinks', 'ratio_intHyperlinks',
       'ratio_extHyperlinks', 'ratio_nullHyperlinks', 'nb_extCSS',
       'ratio_intRedirection', 'ratio_extRedirection', 'ratio_intErrors',
       'ratio_extErrors', 'login_form', 'external_favicon', 'links_in_tags',
       'submit_email', 'ratio_intMedia', 'ratio_extMedia', 'sfh', 'iframe',
       'popup_window', 'safe_anchor', 'onmouseover', 'right_clic',
       'empty_title', 'domain_in_title', 'domain_with_copyright',
       'whois_registered_domain', 'domain_registration_length', 'domain_age',
       'web_traffic', 'dns_record', 'google_index', 'page_rank', 'status'],
      dtype='object')

### Questão 3

Quais os tipos de dados presentes?

In [ ]:
df.describe()

### Questão 4

Existem valores ausentes? Em quais colunas?

In [15]:
df.isnull().sum()

url                0
length_url         0
length_hostname    0
ip                 0
nb_dots            0
                  ..
web_traffic        0
dns_record         0
google_index       0
page_rank          0
status             0
Length: 89, dtype: int64

### Questão 5

Existem registros duplicados?

In [16]:
df.shape

(11430, 89)

In [17]:
df1 = df.drop_duplicates()

In [18]:
df1.shape

(11430, 89)

### Questão 6

Quantos valores únicos existem em uma coluna categórica?

In [ ]:
df.head(2)

In [ ]:
df['status'].value_counts()

### Questão 7

Qual coluna possui maior quantidade de valores distintos?

In [19]:
coluna_com_mais_unicos = df.nunique().idxmax()
quantidade_valores = df[coluna_com_mais_unicos].nunique()
print(df.nunique().sort_values(ascending=False))

url                     11429
web_traffic              4744
domain_age               4430
ratio_intHyperlinks      3131
ratio_extHyperlinks      3131
                        ...
sfh                         1
ratio_nullHyperlinks        1
submit_email                1
ratio_intRedirection        1
ratio_intErrors             1
Length: 89, dtype: int64

### Questão 8

Mostre uma amostra aleatória do dataset.

In [20]:
df.sample(5)

,url,length_url,length_hostname,ip,nb_dots,nb_hyphens,nb_at,nb_qm,nb_and,nb_or,...,domain_in_title,domain_with_copyright,whois_registered_domain,domain_registration_length,domain_age,web_traffic,dns_record,google_index,page_rank,status
9373,http://trbetasusgirisimiz.blogspot.com,38,31,0,2,0,0,0,0,0,...,1,0,0,374,7295,0,0,1,5,phishing
6086,http://www.Cisco.com/c/en/us/products/ios-nx-o...,102,13,0,3,6,0,0,0,0,...,0,0,1,662,12123,1006,0,0,7,legitimate
4229,http://simulatelive.com/product-reviews/simula...,91,16,0,1,6,0,0,0,0,...,1,1,0,35,2157,2030898,0,0,1,legitimate
5478,http://sandlewoodlilakristen.blogspot.com/,42,34,0,2,0,0,0,0,0,...,1,1,0,372,7297,2388565,0,0,5,legitimate
2823,http://www.linfo.org/standard_error.html,40,13,0,3,0,0,0,0,0,...,1,1,0,268,5575,126204,0,0,5,legitimate

## 2. Seleção e Filtragem

### Questão 1

Filtre registros com valores acima da média em uma coluna numérica.

In [ ]:
df['length_url'].mean()

In [ ]:
df[df['length_url'] > 61.12668416447944]

### Questão 2

Filtre registros pertencentes a uma categoria específica.

In [ ]:
df[df['status'] == 'phishing']

### Questão 3

Filtre registros com múltiplas condições.

In [ ]:
df[(df['status'] == 'phishing') | (df['length_url'] > 61.12668416447944) ]

### Questão 4

Filtre registros contendo valores nulos.

In [30]:
linhas_com_nulos = df[df.isnull().any(axis=1)]
print(linhas_com_nulos)

Empty DataFrame
Columns: [url, length_url, length_hostname, ip, nb_dots, nb_hyphens, nb_at, nb_qm, nb_and, nb_or, nb_eq, nb_underscore, nb_tilde, nb_percent, nb_slash, nb_star, nb_colon, nb_comma, nb_semicolumn, nb_dollar, nb_space, nb_www, nb_com, nb_dslash, http_in_path, https_token, ratio_digits_url, ratio_digits_host, punycode, port, tld_in_path, tld_in_subdomain, abnormal_subdomain, nb_subdomains, prefix_suffix, random_domain, shortening_service, path_extension, nb_redirection, nb_external_redirection, length_words_raw, char_repeat, shortest_words_raw, shortest_word_host, shortest_word_path, longest_words_raw, longest_word_host, longest_word_path, avg_words_raw, avg_word_host, avg_word_path, phish_hints, domain_in_brand, brand_in_subdomain, brand_in_path, suspecious_tld, statistical_report, nb_hyperlinks, ratio_intHyperlinks, ratio_extHyperlinks, ratio_nullHyperlinks, nb_extCSS, ratio_intRedirection, ratio_extRedirection, ratio_intErrors, ratio_extErrors, login_form, external_favicon, links_in_tags, submit_email, ratio_intMedia, ratio_extMedia, sfh, iframe, popup_window, safe_anchor, onmouseover, right_clic, empty_title, domain_in_title, domain_with_copyright, whois_registered_domain, domain_registration_length, domain_age, web_traffic, dns_record, google_index, page_rank, status]
Index: []

[0 rows x 89 columns]

### Questão 5

Filtre registros dentro de um intervalo de valores.

In [ ]:
# Sua resposta aqui

## 3. Estatística Descritiva

### Questão 1

Calcule média, mediana, mínimo, máximo e desvio padrão.

In [ ]:
df.describe()

### Questão 2

Identifique os registros acima da média.

In [ ]:
df[df['length_url'] > media]

### Questão 3

Identifique os registros abaixo da mediana.

In [21]:
mediana_url = df['length_url'].median()
registros_acima_mediana = df[df['length_url'] > mediana_url]
print(registros_acima_mediana)

                                                     url  length_url  \
1      http://shadetreetechnology.com/V4/validation/a...          77
2      https://support-appleld.com.secureupdate.duila...         126
4      http://www.iracing.com/tracks/gateway-motorspo...          55
7      http://www.shadetreetechnology.com/V4/validati...          81
9      https://parade.com/425836/joshwigler/the-amazi...         104
...                                                  ...         ...
11423  http://www.dmega.co.kr/dmega/data/qna/sec/page...          85
11424  http://www.answers.com/Q/What_are_the_sizes_of...          62
11426  http://www.budgetbots.com/server.php/Server%20...          84
11427  https://www.facebook.com/Interactive-Televisio...         105
11429  http://174.139.46.123/ap/signin?openid.pape.ma...         477

       length_hostname  ip  nb_dots  nb_hyphens  nb_at  nb_qm  nb_and  nb_or  \
1                   23   1        1           0      0      0       0      0
2                   50   1        4           1      0      1       2      0
4                   15   0        2           2      0      0       0      0
7                   27   1        2           0      0      0       0      0
9                   10   0        1          10      0      0       0      0
...                ...  ..      ...         ...    ...    ...     ...    ...
11423               15   0        4           0      0      1       0      0
11424               15   0        2           0      0      0       0      0
11426               18   0        5           0      1      1       0      0
11427               16   1        2           6      0      1       0      0
11429               14   1       24           0      1      1       9      0

       ...  domain_in_title  domain_with_copyright  whois_registered_domain  \
1      ...                1                      0                        0
2      ...                1                      0                        0
4      ...                0                      1                        0
7      ...                1                      0                        0
9      ...                1                      0                        0
...    ...              ...                    ...                      ...
11423  ...                0                      1                        0
11424  ...                0                      1                        0
11426  ...                1                      0                        0
11427  ...                0                      0                        0
11429  ...                1                      1                        1

       domain_registration_length  domain_age  web_traffic  dns_record  \
1                              77        5767            0           0
2                              14        4004      5828815           0
4                             224        8175         8725           0
7                              76        5767            0           0
9                             128        9368         6774           0
...                           ...         ...          ...         ...
11423                         293        5186     10408014           0
11424                         506        8829         2635           0
11426                         211        6728            0           0
11427                        2809        8515            8           0
11429                           0          -1            0           1

       google_index  page_rank      status
1                 1          2    phishing
2                 1          0    phishing
4                 0          6  legitimate
7                 1          2    phishing
9                 0          5  legitimate
...             ...        ...         ...
11423             1          1    phishing
11424             1          6  legitimate
11426             1          0    phishing
11427             1         10  legitimate
11429             1          0    phishing

[5678 rows x 89 columns]

### Questão 4

Qual coluna numérica possui maior variabilidade?

In [ ]:
# Sua resposta aqui

## 4. Ordenação

### Questão 1

Ordene o dataset de forma crescente.

In [14]:
# Sudataset_ordenado = df.sort_values(by='length_url', ascending=True)
print(dataset_ordenado.head())

                                                    url  length_url  \
9002  https://dev.seatassignmate.net/latam/payment_o...        1641
1444  http://licogi18.com.vn/login.microsoftonline.c...        1386
8186  http://licogi18.com.vn/login.microsoftonline.c...        1386
6791  http://systemupdatingserverservice.secureonlin...         938
8738  https://bidstack.cloudflareaccess.com/cdn-cgi/...         907

      length_hostname  ip  nb_dots  nb_hyphens  nb_at  nb_qm  nb_and  nb_or  \
9002               22   1        3          32      0      1       0      0
1444               15   1       13          11      0      3      19      0
8186               15   1       13          11      0      3      19      0
6791               56   1        3           0      0      1       1      0
8738               29   1        6          10      0      1       3      0

      ...  domain_in_title  domain_with_copyright  whois_registered_domain  \
9002  ...                1                      1                        0
1444  ...                1                      0                        1
8186  ...                1                      0                        1
6791  ...                1                      0                        1
8738  ...                1                      0                        0

      domain_registration_length  domain_age  web_traffic  dns_record  \
9002                        1228        1328            0           0
1444                           0          -1      9366151           0
8186                           0          -1      9366151           0
6791                           0          16            0           0
8738                        2614        1037        13295           0

      google_index  page_rank    status
9002             0          0  phishing
1444             0          2  phishing
8186             0          2  phishing
6791             1          0  phishing
8738             1          2  phishing

[5 rows x 89 columns]

### Questão 2

Ordene o dataset de forma decrescente.

In [13]:
dataset_ordenado = df.sort_values(by='length_url', ascending=False)
print(dataset_ordenado.head())

                                                    url  length_url  \
9002  https://dev.seatassignmate.net/latam/payment_o...        1641
1444  http://licogi18.com.vn/login.microsoftonline.c...        1386
8186  http://licogi18.com.vn/login.microsoftonline.c...        1386
6791  http://systemupdatingserverservice.secureonlin...         938
8738  https://bidstack.cloudflareaccess.com/cdn-cgi/...         907

      length_hostname  ip  nb_dots  nb_hyphens  nb_at  nb_qm  nb_and  nb_or  \
9002               22   1        3          32      0      1       0      0
1444               15   1       13          11      0      3      19      0
8186               15   1       13          11      0      3      19      0
6791               56   1        3           0      0      1       1      0
8738               29   1        6          10      0      1       3      0

      ...  domain_in_title  domain_with_copyright  whois_registered_domain  \
9002  ...                1                      1                        0
1444  ...                1                      0                        1
8186  ...                1                      0                        1
6791  ...                1                      0                        1
8738  ...                1                      0                        0

      domain_registration_length  domain_age  web_traffic  dns_record  \
9002                        1228        1328            0           0
1444                           0          -1      9366151           0
8186                           0          -1      9366151           0
6791                           0          16            0           0
8738                        2614        1037        13295           0

      google_index  page_rank    status
9002             0          0  phishing
1444             0          2  phishing
8186             0          2  phishing
6791             1          0  phishing
8738             1          2  phishing

[5 rows x 89 columns]

### Questão 3

Mostre os 5 maiores registros.

In [11]:
maiores_urls = df.sort_values(by='length_url', ascending=False).head(5)
print(maiores_urls)

                                                    url  length_url  \
9002  https://dev.seatassignmate.net/latam/payment_o...        1641
1444  http://licogi18.com.vn/login.microsoftonline.c...        1386
8186  http://licogi18.com.vn/login.microsoftonline.c...        1386
6791  http://systemupdatingserverservice.secureonlin...         938
8738  https://bidstack.cloudflareaccess.com/cdn-cgi/...         907

      length_hostname  ip  nb_dots  nb_hyphens  nb_at  nb_qm  nb_and  nb_or  \
9002               22   1        3          32      0      1       0      0
1444               15   1       13          11      0      3      19      0
8186               15   1       13          11      0      3      19      0
6791               56   1        3           0      0      1       1      0
8738               29   1        6          10      0      1       3      0

      ...  domain_in_title  domain_with_copyright  whois_registered_domain  \
9002  ...                1                      1                        0
1444  ...                1                      0                        1
8186  ...                1                      0                        1
6791  ...                1                      0                        1
8738  ...                1                      0                        0

      domain_registration_length  domain_age  web_traffic  dns_record  \
9002                        1228        1328            0           0
1444                           0          -1      9366151           0
8186                           0          -1      9366151           0
6791                           0          16            0           0
8738                        2614        1037        13295           0

      google_index  page_rank    status
9002             0          0  phishing
1444             0          2  phishing
8186             0          2  phishing
6791             1          0  phishing
8738             1          2  phishing

[5 rows x 89 columns]

### Questão 4

Mostre os 5 menores registros.

In [12]:
menores_urls = df.sort_values(by='length_url', ascending=True).head(5)
print(menores_urls)

                url  length_url  length_hostname  ip  nb_dots  nb_hyphens  \
3749   http://hz.by          12                5   0        1           0
1963  http://ohi.im          13                6   0        1           0
8258  http://yfm.lk          13                6   0        1           0
7310  http://ati.su          13                6   0        1           0
1560  http://gs8.hk          13                6   0        1           0

      nb_at  nb_qm  nb_and  nb_or  ...  domain_in_title  \
3749      0      0       0      0  ...                1
1963      0      0       0      0  ...                0
8258      0      0       0      0  ...                1
7310      0      0       0      0  ...                1
1560      0      0       0      0  ...                1

      domain_with_copyright  whois_registered_domain  \
3749                      1                        0
1963                      0                        0
8258                      1                        1
7310                      1                        0
1560                      1                        0

      domain_registration_length  domain_age  web_traffic  dns_record  \
3749                         689          -1      8154406           0
1963                         408          -1       676515           0
8258                           0          -1      1271273           0
7310                          36        5442        13336           0
1560                        1544          -1      1779698           0

      google_index  page_rank      status
3749             0          1  legitimate
1963             0          2  legitimate
8258             0          2  legitimate
7310             0          4  legitimate
1560             0          2  legitimate

[5 rows x 89 columns]

### Questão 5

Ordene utilizando múltiplas colunas.

In [27]:
df_ordenado = df.sort_values(by=['length_hostname', 'length_url'])

print(df_ordenado.head())

                  url  length_url  length_hostname  ip  nb_dots  nb_hyphens  \
403   http://3.ly/uja          15                4   0        1           0
2463  http://3.ly/uhW          15                4   0        1           0
5572  http://3.ly/uh9          15                4   0        1           0
8758  http://3.ly/uhP          15                4   0        1           0
9251  http://3.ly/uhJ          15                4   0        1           0

      nb_at  nb_qm  nb_and  nb_or  ...  domain_in_title  \
403       0      0       0      0  ...                1
2463      0      0       0      0  ...                1
5572      0      0       0      0  ...                1
8758      0      0       0      0  ...                1
9251      0      0       0      0  ...                1

      domain_with_copyright  whois_registered_domain  \
403                       1                        0
2463                      1                        0
5572                      1                        0
8758                      1                        0
9251                      1                        0

      domain_registration_length  domain_age  web_traffic  dns_record  \
403                            0          -1            0           0
2463                           0          -1            0           0
5572                           0          -1            0           0
8758                           0          -1            0           0
9251                           0          -1            0           0

      google_index  page_rank    status
403              1          4  phishing
2463             1          4  phishing
5572             1          4  phishing
8758             1          4  phishing
9251             1          4  phishing

[5 rows x 89 columns]

## 6. Tratamento de Dados

### Questão 1

Identifique valores ausentes.

In [28]:
valores_nulos = df.isnull().sum()
print(valores_nulos)

url                0
length_url         0
length_hostname    0
ip                 0
nb_dots            0
                  ..
web_traffic        0
dns_record         0
google_index       0
page_rank          0
status             0
Length: 89, dtype: int64

### Questão 4

Renomeie colunas.

In [29]:
# Para renomar a coluna testei o comando mas não executei neste dataset para não mudar ele

df.rename(columns={'length_url': 'length_url'}, inplace=True)

### Questão 5

Crie uma nova coluna baseada em operações matemáticas.

In [ ]:
# Sua resposta aqui

## 9. Visualização de Dados

### Questão 1

Crie um gráfico de barras.

In [ ]:
# Sua resposta aqui

### Questão 2

Crie um histograma.

In [ ]:
# Sua resposta aqui

### Questão 3

Crie um gráfico de dispersão.

In [ ]:
# Sua resposta aqui

### Questão 4

Crie um boxplot.

In [ ]:
# Sua resposta aqui

### Questão 5

Escolha o gráfico mais adequado para representar os dados.

In [ ]:
# Sua resposta aqui